[package]
name = "system_info_monitor"
version = "0.1.0"
edition = "2024"
authors = ["Veper <github.com/VxxxxC>"]

[dependencies]
color-eyre = "0.6.3"
ratatui = { version = "0.29.0" }
crossterm = "0.28.1"
sysinfo = "0.37.0"